Repository whileTrueDev/onadWeb, pull requests merged in 2019-08, with the labels that each got.

#1 [Documentation] Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#6 [UPDATE] chan => dev 클로즈 베타 종료 관련
  client/src/components/Dashboard/views/marketer/Dashboard/ValueChart.jsx
  client/src/components/Main/index.jsx
  client/src/components/Main/views/CTA/ProductCTA.jsx
  client/src/components/Main/views/Login/BetaDialog.jsx
  service/app.js
  service/routes/creator.js
  service/routes/dashboard.js
  service/routes/login.js
  service/routes/mailer.js
  service/routes/marketer.js
  service/routes/regist.js
Labels: enhancement

#5 [UPDATE] Hwasurr -> dev
  README.md
  client/src/components/Common/ShutDownCloseBeta.jsx
  client/src/components/Dashboard/components/Navbars/AdminNavbarLinks.jsx
  client/src/components/Dashboard/components/Navbars/Notification.jsx
  client/src/index.jsx
Labels: enhancement

#7 [update] Dev -> Master
  README.md
  client/src/components/Common/ShutDownCloseBeta.jsx
  client/src/components/Dashboard/components/Navbars/AdminNavbarLinks.jsx
  client/src/components/Dashboard/components/Navbars/Notification.jsx
  client/src/components/Dashboard/views/marketer/Dashboard/ValueChart.jsx
  client/src/components/Main/index.jsx
  client/src/components/Main/views/CTA/ProductCTA.jsx
  client/src/components/Main/views/Login/BetaDialog.jsx
  client/src/index.jsx
  service/app.js
  service/routes/creator.js
  service/routes/dashboard.js
  service/routes/login.js
  service/routes/mailer.js
  service/routes/marketer.js
  service/routes/regist.js
Labels: enhancement, update

#8 [Update] Hwasurr 1 -> dev
  client/src/components/Common/NotFound.jsx
  client/src/components/Common/ShutDownCloseBeta.jsx
  client/src/components/Dashboard/components/Navbars/AdminNavbarLinks.jsx
  client/src/components/Dashboard/components/Navbars/Notification.jsx
  client/src/components/Dashboard/components/Table/Table.jsx
  client/src/components/Dashboard/views/creator/Dashboard/Dashboard.jsx
  client/src/components/Main/views/Login/BetaDialog.jsx
  client/src/index.jsx
  service/passportStrategy.js
Labels: enhancement
